{{- if .Values.secrets.useExternalSecrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: platform-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/platform"
        objectType: "secretsmanager"
        jmesPath:
          - path: WEATHER_API_KEY
            objectAlias: WEATHER_API_KEY
          - path: OPEN_WEATHER_MAP_KEY
            objectAlias: OPEN_WEATHER_MAP_KEY
          - path: WEATHER_STACK_KEY
            objectAlias: WEATHER_STACK_KEY
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: EMAIL_USER
            objectAlias: EMAIL_USER
          - path: EMAIL_PASSWORD
            objectAlias: EMAIL_PASSWORD
  secretObjects:
    - secretName: platform-secret-store
      type: Opaque
      data:
        - objectName: WEATHER_API_KEY
          key: WEATHER_API_KEY
        - objectName: OPEN_WEATHER_MAP_KEY
          key: OPEN_WEATHER_MAP_KEY
        - objectName: WEATHER_STACK_KEY
          key: WEATHER_STACK_KEY
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: EMAIL_USER
          key: EMAIL_USER
        - objectName: EMAIL_PASSWORD
          key: EMAIL_PASSWORD
{{- end }}
