{{- if .Values.secrets.useExternalSecrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secretsmanager-platform
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/platform"
        objectType: "secretsmanager"
        jmesPath:
          {{- range .Values.platformApiGateway.externalSecretKeys }}
          - path: {{ .path }}
            objectAlias: {{ .alias }}
          {{- end }}
          {{- range .Values.platformWeatherService.externalSecretKeys }}
          - path: {{ .path }}
            objectAlias: {{ .alias }}
          {{- end }}
          {{- range .Values.platformSubscriptionService.externalSecretKeys }}
          - path: {{ .path }}
            objectAlias: {{ .alias }}
          {{- end }}
  secretObjects:
    - secretName: platform-secrets-store
      type: Opaque
      data:
        {{- range .Values.platformApiGateway.externalSecretKeys }}
        - objectName: {{ .alias }}
          key: {{ .alias }}
        {{- end }}
        {{- range .Values.platformWeatherService.externalSecretKeys }}
        - objectName: {{ .alias }}
          key: {{ .alias }}
        {{- end }}
        {{- range .Values.platformSubscriptionService.externalSecretKeys }}
        - objectName: {{ .alias }}
          key: {{ .alias }}
        {{- end }}
{{- end }}
