apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/GenesisEducationKyiv/software-engineering-school-5-0-vikkyvl
    targetRevision: patuzhni-35
    path: deployment/kube/charts/platform
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
