apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-web-app
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-web
                port:
                  number: {{ .Values.service.port }}