version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'

  loki:
    image: grafana/loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - ./loki-data:/loki

  grafana:
    image: grafana/grafana
    ports:
      - "3500:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

#  weather-service:
#    build: ./weather-service
#    ports:
#      - '3001:3000'
#    depends_on:
#      - rabbitmq
#      - postgres
#
#  subscription-service:
#    build: ./subscription-service
#    ports:
#      - '3002:3000'
#    depends_on:
#      - rabbitmq
#      - postgres
#
#  api-gateway:
#    build: ./api-gateway
#    ports:
#      - '3000:3000'
#    depends_on:
#      - weather-service
#      - subscription-service

volumes:
  pg_data:
  grafana-storage:
