global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'weather-service'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'subscription-service'
    static_configs:
      - targets: ['host.docker.internal:3002']
