{{- if .Values.postgres.useExternalSecrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/postgres"
        objectType: "secretsmanager"
        jmesPath:
          - path: POSTGRES_USER
            objectAlias: POSTGRES_USER
          - path: POSTGRES_PASSWORD
            objectAlias: POSTGRES_PASSWORD
          - path: POSTGRES_DB
            objectAlias: POSTGRES_DB
  secretObjects:
    - secretName: postgres-secret-store
      type: Opaque
      data:
        - objectName: POSTGRES_USER
          key: POSTGRES_USER
        - objectName: POSTGRES_PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: POSTGRES_DB
          key: POSTGRES_DB
{{- end }}
