{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: registry
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
{{- end }}
