name: Auto-Tag & Push Docker Images

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine next version
        id: tag
        run: |
          LAST_TAG=$(git tag --sort=-v:refname | grep '^v' | tail -n1)
          if [[ "$LAST_TAG" =~ ^v([0-9]+)$ ]]; then
            NEXT_VERSION=$(( ${BASH_REMATCH[1]} + 1 ))
          else
            NEXT_VERSION=1
          fi
          echo "NEW_TAG=v$NEXT_VERSION" >> $GITHUB_ENV
          echo "tag=v$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push tag to GitHub
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
