name: Lint all services

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
  api-gateway-lint:
      runs-on: ubuntu-latest
      defaults:
          run:
              working-directory: ./api-gateway
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
                node-version: 18
                cache: 'npm'
          - run: npm ci
          - run: npm run lint


  weather-service-lint:
      runs-on: ubuntu-latest
      defaults:
          run:
              working-directory: ./weather-service
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
                node-version: 18
                cache: 'npm'
          - run: npm ci
          - run: npm run lint

  subscription-service-lint:
      runs-on: ubuntu-latest
      defaults:
          run:
              working-directory: ./subscription-service
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
                node-version: 18
                cache: 'npm'
          - run: npm ci
          - run: npm run lint
