name: Lint all services

on:
    push:
        branches: ["**"]
    pull_request:
        branches: [main]
jobs:
    platform-app:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./platform-app
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - run: npm ci
            - run: npm run lint
            - run: npm run test:cov
            - uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
#  api-gateway-lint:
#      runs-on: ubuntu-latest
#      defaults:
#          run:
#              working-directory: ./api-gateway
#      steps:
#          - uses: actions/checkout@v4
#          - uses: actions/setup-node@v4
#            with:
#                node-version: 18
#          - run: npm ci
#          - run: npm run lint
#
#
#  weather-service-lint:
#      runs-on: ubuntu-latest
#      defaults:
#          run:
#              working-directory: ./weather-service
#      steps:
#          - uses: actions/checkout@v4
#          - uses: actions/setup-node@v4
#            with:
#                node-version: 18
#          - run: npm ci
#          - run: npm run lint
#
#  subscription-service-lint:
#      runs-on: ubuntu-latest
#      defaults:
#          run:
#              working-directory: ./subscription-service
#      steps:
#          - uses: actions/checkout@v4
#          - uses: actions/setup-node@v4
#            with:
#                node-version: 18
#          - run: npm ci
#          - run: npm run lint
